---
title: "p8105_hw5_jw4690"
author: "Jingxi Wang"
date: "2024-11-06"
output: github_document
---

```{r setup, echo = FALSE, message = FALSE}
library(tidyverse)
```

## Problem 1

```{r}
bday_sim = function(n) {
  bdays = sample(1:365, size = n, replace = TRUE)
  duplicate = length(unique(bdays)) < n
  return(duplicate)
}

sim_res = expand_grid(
  n = 2:50,
  iter = 1:10000
) |>
  mutate(res = map_lgl(n, bday_sim)) |>
  group_by(n) |>
  summarize(prob = mean(res))

sim_res_plot = sim_res |>
  ggplot(aes(x = n, y = prob)) +
  geom_line() +
  labs(
    title = "Probability of Shared Birthdays as a Function of Group Size",
    x = "Group Size",
    y = "Probability of at least two people sharing a birthday"
  )

sim_res_plot
```

The probability of shared birthdays increases sharply as the group size grows. As the group size reaches around 50, the probability approaches nearly 100%, indicating that it’s almost certain that at least two people in the group will share a birthday. 


## Problem 2

```{r}
sim_power = function(mu, n = 30, sigma = 5, alpha = 0.05) {
  sim_data = 
    tibble(
      x = rnorm(n, mean = mu, sd = sigma)
      )
  
  t_test = t.test(sim_data$x, mu = 0)
  result = broom::tidy(t_test)
  
  out_df = tibble(
    estimate = result$estimate,
    p_value = result$p.value
  )
  
  return(out_df)
}
```

```{r}
n_sim = 5000
mu_values = c(0, 1, 2, 3, 4, 5, 6)

sim_res_2 = expand_grid(
  mu = mu_values,
  iter = 1:n_sim
) |>
  mutate(sim_output = map(mu, sim_power)) |>
  unnest(sim_output) |>
  group_by(mu) |>
  summarize(
    power = mean(p_value < 0.05),
    avg_estimate = mean(estimate),
    avg_estimate_rejected = mean(estimate[p_value < 0.05])
  )
```

